name: "Terraform apply"
on: 
  push:
    branches:
    - main
jobs:
  deployment:
    name: Infra deployment
    runs-on: Ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Init
      run: terraform init

    - name: Terraform Plan
      id: Plan
      if: github.event == "push"
      run:  terraform plan
      continue-on-error: true

    - name: Terraform plan status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Deploy
      if: github.ref == 'refs/head/master' && github.event_name == 'push'
      run: terraform apply -auto-approve