name: "Terraform apply"
on: workflow_dispatch
jobs:
  dev:
    name: Dev-destroy
    runs-on: Ubuntu-latest
    environment: stage
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'      
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Dev Init
      run: terraform init -backend-config=dev.conf
    - name: Destroy
      run: terraform destroy -var-file=dev.tfvars -auto-approve
  stage:
    name: Stage-destroy
    runs-on: Ubuntu-latest
    environment: stage
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'
      environment: dev
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Stage Init
      run: terraform init -backend-config=stage.conf
    - name: Destroy
      run: terraform destroy -var-file=stage.tfvars -auto-approve